path:
  ckpt_path: "/ssd_scratch/cvit/neha/output/ckpt/Bli_DT"
  log_path: "/ssd_scratch/cvit/neha/output/log/Bli_DT"
  result_path: "./output/result/Bli_DT"
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 1900000
  log_step: 1000
  synth_step: 1000
  val_step: 1000
  save_step: 20000
